services:
  redis:
    container_name: ${REDIS_DB_CONTAINER_NAME}
    user: "999:999"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: ${REDIS_DB_IMAGE}
    volumes:
      - ${PWD}/storage/redis_cart_data/redis_data:/data
      - ${PWD}/storage/redis_cart_data/redis.conf:/data/redis.conf
    environment:
      - REDIS_USERNAME=${REDIS_DB_USERNAME}
      - REDIS_PASSWORD=${REDIS_DB_PASSWORD}
      - REDIS_USER=${REDIS_DB_USERNAME}
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: "65536"
    command: 
      - /bin/sh
      - -c
      - |
        # Remove vm.overcommit_memory from redis.conf to prevent warnings
        # Config is now in /data/redis.conf
        exec redis-server /data/redis.conf
        command: ["redis-server", "/data/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "--user", "${REDIS_USERNAME}", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 100032
        hard: 100032

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
      - "${NGINX_PORT}:8080"
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_CONTAINER_PORT}"
    volumes:
      - ${PWD}/storage/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ${PWD}/storage/nginx/nginx_data/conf.d/http.conf:/etc/nginx/conf.d/http.conf
      #- ${PWD}/storage/nginx/nginx_data/conf.d/stream.conf:/etc/nginx/conf.d/stream.conf
      - ${PWD}/storage/nginx/empty.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/storage/nginx/nginx_data/logs:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - redis  
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  redis_data:
  nginx_data:
