services:
  redis-node-1:
    container_name: redis-node-1
    user: "999:999"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: ${REDIS_DB_IMAGE}
    volumes:
      - ${PWD}/storage/redis_node_1:/data
      - ${PWD}/storage/redis_cart_data/redis.conf:/data/redis.conf
    environment:
      - REDIS_USERNAME=${REDIS_DB_USERNAME}
      - REDIS_PASSWORD=${REDIS_DB_PASSWORD}
      - REDIS_USER=${REDIS_DB_USERNAME}
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: "65536"
    command: 
      - /bin/sh
      - -c
      - |
        exec redis-server /data/redis.conf --port ${REDIS_NODE_1_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "${REDIS_NODE_1_PORT}", "--user", "${REDIS_USERNAME}", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 100032
        hard: 100032
    networks:
      - redis-cluster

  redis-node-2:
    container_name: redis-node-2
    user: "999:999"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: ${REDIS_DB_IMAGE}
    volumes:
      - ${PWD}/storage/redis_node_2:/data
      - ${PWD}/storage/redis_cart_data/redis.conf:/data/redis.conf
    environment:
      - REDIS_USERNAME=${REDIS_DB_USERNAME}
      - REDIS_PASSWORD=${REDIS_DB_PASSWORD}
      - REDIS_USER=${REDIS_DB_USERNAME}
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: "65536"
    command: 
      - /bin/sh
      - -c
      - |
        exec redis-server /data/redis.conf --port ${REDIS_NODE_2_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "${REDIS_NODE_2_PORT}", "--user", "${REDIS_USERNAME}", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 100032
        hard: 100032
    networks:
      - redis-cluster

  redis-node-3:
    container_name: redis-node-3
    user: "999:999"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: ${REDIS_DB_IMAGE}
    volumes:
      - ${PWD}/storage/redis_node_3:/data
      - ${PWD}/storage/redis_cart_data/redis.conf:/data/redis.conf
    environment:
      - REDIS_USERNAME=${REDIS_DB_USERNAME}
      - REDIS_PASSWORD=${REDIS_DB_PASSWORD}
      - REDIS_USER=${REDIS_DB_USERNAME}
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: "65536"
    command: 
      - /bin/sh
      - -c
      - |
        exec redis-server /data/redis.conf --port ${REDIS_NODE_3_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "${REDIS_NODE_3_PORT}", "--user", "${REDIS_USERNAME}", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 100032
        hard: 100032
    networks:
      - redis-cluster

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
      - "${NGINX_PORT}:${NGINX_PORT}"
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_CONTAINER_PORT}"
    volumes:
      - ${PWD}/storage/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/storage/nginx/empty.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/storage/nginx/nginx_data/logs:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge

volumes:
  redis_node_1:
  redis_node_2:
  redis_node_3:
  nginx_data:
